export const FETCH_DESTINATIONS = 'FETCH_DESTINATIONS';
export const ADD_DESTINATION = 'ADD_DESTINATION';
export const FETCH_DESTINATION = 'FETCH_DESTINATION';
export const SEARCH_DESTINATIONS = 'SEARCH_DESTINATIONS';
export const DELETE_DESTINATION_SUCCESS = 'DELETE_DESTINATION_SUCCESS';
export const FETCH_DESTINATIONS_SUCCESS = 'FETCH_DESTINATIONS_SUCCESS';